language: python
python:
  - 3.5
  - 3.6

branches:
  only:
  - master
  - dev

install:
  - pip install nose
  - pip install python-coveralls coverage
script:
  - nosetests --with-coverage
after_success:
  - coveralls
